name: Deploy JBake site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install JBake
        run: |
          curl -L https://github.com/jbake-org/jbake/releases/download/v2.6.7/jbake-2.6.7-bin.zip -o jbake.zip
          unzip jbake.zip -d jbake
          sudo mv jbake/jbake-2.6.7-bin /opt/jbake
          sudo ln -s /opt/jbake/bin/jbake /usr/local/bin/jbake

      - name: Bake site
        run: jbake -b

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
